apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk8s-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jk8s-lab
  template:
    metadata:
      labels:
        app: jk8s-lab
    spec:
      containers:
        - name: jk8s-con
          image: jidan/jk8s
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jk8s-svc1
spec:
  type: NodePort
  selector:
    app: jk8s-lab
  ports:
    - name: default
      protocol: TCP