// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFeedImage = "feed_image"

// FeedImage mapped from table <feed_image>
type FeedImage struct {
	ID        int64          `gorm:"column:id;primaryKey" json:"id"`         // ID
	FeedID    int64          `gorm:"column:feed_id;not null" json:"feed_id"` // 动态ID
	ImgURL    string         `gorm:"column:img_url;not null" json:"img_url"` // 图片URL
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName FeedImage's table name
func (*FeedImage) TableName() string {
	return TableNameFeedImage
}
