// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoadminPermission = "goadmin_permissions"

// GoadminPermission mapped from table <goadmin_permissions>
type GoadminPermission struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Slug       string    `gorm:"column:slug;not null" json:"slug"`
	HTTPMethod string    `gorm:"column:http_method" json:"http_method"`
	HTTPPath   string    `gorm:"column:http_path;not null" json:"http_path"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminPermission's table name
func (*GoadminPermission) TableName() string {
	return TableNameGoadminPermission
}
