// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ijidan/jsocial/internal/model"
)

func newGroup(db *gorm.DB) group {
	_group := group{}

	_group.groupDo.UseDB(db)
	_group.groupDo.UseModel(&model.Group{})

	tableName := _group.groupDo.TableName()
	_group.ALL = field.NewAsterisk(tableName)
	_group.ID = field.NewInt64(tableName, "id")
	_group.Name = field.NewString(tableName, "name")
	_group.Introduction = field.NewString(tableName, "introduction")
	_group.Extra = field.NewString(tableName, "extra")
	_group.AtavarURL = field.NewString(tableName, "atavar_url")
	_group.UserID = field.NewInt64(tableName, "user_id")
	_group.CreatedAt = field.NewTime(tableName, "created_at")
	_group.UpdatedAt = field.NewTime(tableName, "updated_at")
	_group.DeletedAt = field.NewField(tableName, "deleted_at")
	_group.GroupUser = groupManyToManyGroupUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GroupUser", "model.GroupUser"),
	}

	_group.fillFieldMap()

	return _group
}

type group struct {
	groupDo groupDo

	ALL          field.Asterisk
	ID           field.Int64  // 自增主键
	Name         field.String // 群组名称
	Introduction field.String // 群组简介
	Extra        field.String // 附加属性
	AtavarURL    field.String // 头像
	UserID       field.Int64  // 群主ID
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	DeletedAt    field.Field  // 删除时间
	GroupUser    groupManyToManyGroupUser

	fieldMap map[string]field.Expr
}

func (g group) Table(newTableName string) *group {
	g.groupDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g group) As(alias string) *group {
	g.groupDo.DO = *(g.groupDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *group) updateTableName(table string) *group {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Name = field.NewString(table, "name")
	g.Introduction = field.NewString(table, "introduction")
	g.Extra = field.NewString(table, "extra")
	g.AtavarURL = field.NewString(table, "atavar_url")
	g.UserID = field.NewInt64(table, "user_id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *group) WithContext(ctx context.Context) *groupDo { return g.groupDo.WithContext(ctx) }

func (g group) TableName() string { return g.groupDo.TableName() }

func (g group) Alias() string { return g.groupDo.Alias() }

func (g *group) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *group) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 10)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["introduction"] = g.Introduction
	g.fieldMap["extra"] = g.Extra
	g.fieldMap["atavar_url"] = g.AtavarURL
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt

}

func (g group) clone(db *gorm.DB) group {
	g.groupDo.ReplaceDB(db)
	return g
}

type groupManyToManyGroupUser struct {
	db *gorm.DB

	field.RelationField
}

func (a groupManyToManyGroupUser) Where(conds ...field.Expr) *groupManyToManyGroupUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a groupManyToManyGroupUser) WithContext(ctx context.Context) *groupManyToManyGroupUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a groupManyToManyGroupUser) Model(m *model.Group) *groupManyToManyGroupUserTx {
	return &groupManyToManyGroupUserTx{a.db.Model(m).Association(a.Name())}
}

type groupManyToManyGroupUserTx struct{ tx *gorm.Association }

func (a groupManyToManyGroupUserTx) Find() (result []*model.GroupUser, err error) {
	return result, a.tx.Find(&result)
}

func (a groupManyToManyGroupUserTx) Append(values ...*model.GroupUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a groupManyToManyGroupUserTx) Replace(values ...*model.GroupUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a groupManyToManyGroupUserTx) Delete(values ...*model.GroupUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a groupManyToManyGroupUserTx) Clear() error {
	return a.tx.Clear()
}

func (a groupManyToManyGroupUserTx) Count() int64 {
	return a.tx.Count()
}

type groupDo struct{ gen.DO }

func (g groupDo) Debug() *groupDo {
	return g.withDO(g.DO.Debug())
}

func (g groupDo) WithContext(ctx context.Context) *groupDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupDo) ReadDB() *groupDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupDo) WriteDB() *groupDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupDo) Clauses(conds ...clause.Expression) *groupDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupDo) Returning(value interface{}, columns ...string) *groupDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupDo) Not(conds ...gen.Condition) *groupDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupDo) Or(conds ...gen.Condition) *groupDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupDo) Select(conds ...field.Expr) *groupDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupDo) Where(conds ...gen.Condition) *groupDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *groupDo {
	return g.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (g groupDo) Order(conds ...field.Expr) *groupDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupDo) Distinct(cols ...field.Expr) *groupDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupDo) Omit(cols ...field.Expr) *groupDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupDo) Join(table schema.Tabler, on ...field.Expr) *groupDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *groupDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupDo) RightJoin(table schema.Tabler, on ...field.Expr) *groupDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupDo) Group(cols ...field.Expr) *groupDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupDo) Having(conds ...gen.Condition) *groupDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupDo) Limit(limit int) *groupDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupDo) Offset(offset int) *groupDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *groupDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupDo) Unscoped() *groupDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupDo) Create(values ...*model.Group) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupDo) CreateInBatches(values []*model.Group, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupDo) Save(values ...*model.Group) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupDo) First() (*model.Group, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Group), nil
	}
}

func (g groupDo) Take() (*model.Group, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Group), nil
	}
}

func (g groupDo) Last() (*model.Group, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Group), nil
	}
}

func (g groupDo) Find() ([]*model.Group, error) {
	result, err := g.DO.Find()
	return result.([]*model.Group), err
}

func (g groupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Group, err error) {
	buf := make([]*model.Group, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupDo) FindInBatches(result *[]*model.Group, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupDo) Attrs(attrs ...field.AssignExpr) *groupDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupDo) Assign(attrs ...field.AssignExpr) *groupDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupDo) Joins(fields ...field.RelationField) *groupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupDo) Preload(fields ...field.RelationField) *groupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupDo) FirstOrInit() (*model.Group, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Group), nil
	}
}

func (g groupDo) FirstOrCreate() (*model.Group, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Group), nil
	}
}

func (g groupDo) FindByPage(offset int, limit int) (result []*model.Group, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupDo) Delete(models ...*model.Group) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupDo) withDO(do gen.Dao) *groupDo {
	g.DO = *do.(*gen.DO)
	return g
}
